name: Build_Beta_BTG_CI

on:
  push:
    branches:
      - '**'

jobs:

  react-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: React

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npm run build

  dotnet-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: API/UserPanel

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore

      - run: dotnet build --configuration Release

  python-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Python

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt